version: "3"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "80:80"

  mysql:
    image: mysql:5.7.35
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
